version: '3'

services:
  BibRecServer:
    image: bibrec-server:latest
    build: ./bibrec/server
    user: "1000:1001"
    volumes:
      - ./bibrec/server:/api/src
      - ./data:/api/src/data
    environment:
      - FLASK_DEBUG=false
      - FLASK_APP=app.py
      - RF_VERBOSE=10
      # - RF_RANDOM_STATE=1
    expose:
      - 4000
    ports:
      - "4000:4000"

  BibRecClient:
    image: bibrec-client:latest
    build: ./bibrec/client
    command: npm run dev
    volumes:
      - ./bibrec/client:/app
    ports:
      - "3000:3000"
    depends_on:
      - BibRecServer
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
