version: '3'

services:
  server:
    build: ./server
    volumes:
      - ./server:/api/src
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    expose:
      - 4000
    ports:
      - 4000:4000

  client:
    build: ./client
    command: npm run dev
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
       - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server