version: '3'

services:
  server:
    image: bibrec-server:latest
    build: ./server
    user: "1000:1001"
    volumes:
      - ./server:/api/src
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    expose:
      - 4000
    ports:
      - "4000:4000"

  client:
    image: bibrec-client:latest
    build: ./client
    command: npm run dev
    volumes:
      - ./client/:/app
    ports:
      - "3000:3000"
    depends_on:
      - server
